[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "tangentmode"
version = "0.1.0"
requires-python = ">=3.10"
description = "Automatic differentiation in Python using dual numbers."
readme = "README.md"
license = "LICENSE"

[project.optional-dependencies]
dev = ["pytest>=8", "mypy>=1"]

[tool.setuptools.packages.find]
where = ["src"]